name: semgrep-rules-pr
on: [push, pull_request]
jobs:
  run-test:
    runs-on: ubuntu-latest
    container:
      image: kasterma/semgrep
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make test
